In [ ]:
# Insurance ML Project - EDA
# Objective: understand data and prepare for modeling

## Objetivo
# Prever probabilidade de sinistro em seguros auto

## Target
# coluna: sinistro (0 ou 1)

## Impacto de negócio
#- reduzir prejuízo
#- ajustar precificação

In [1]:
import pandas as pd

df = pd.read_csv("seguro_auto_historico.csv")
df.head()

,id_cliente,ano_contratacao,mes_contratacao,canal_venda,idade,sexo,estado_civil,qtde_filhos,estado,regiao,...,valor_segurado,premio_seguro,franquia,tipo_cobertura,assistencia_24h,carro_reserva,protecao_vidros,classe_bonus,desconto_comercial,sinistro_grave_perda_total_12m
0,100000,2024,12,banco_parceiro,50,F,casado,1,SP,Sudeste,...,67885.85,1704.48,2715.43,intermediaria,0,1,1,10,20.17,0
1,100001,2023,12,telefone,72,F,casado,2,AL,Nordeste,...,72394.33,2594.61,4343.66,intermediaria,1,1,1,10,14.67,0
2,100002,2025,12,app,24,M,solteiro,0,SC,Sul,...,28890.12,1595.85,1444.51,intermediaria,1,1,0,0,5.88,0
3,100003,2024,12,app,38,F,solteiro,3,BA,Nordeste,...,280723.40,7188.11,11228.94,intermediaria,1,1,1,4,9.61,0
4,100004,2020,11,telefone,61,M,divorciado,2,PR,Sul,...,63105.55,1278.45,3155.28,completa,1,0,0,10,7.38,0

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 62 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id_cliente                      100000 non-null  int64
 1   ano_contratacao                 100000 non-null  int64
 2   mes_contratacao                 100000 non-null  int64
 3   canal_venda                     100000 non-null  object
 4   idade                           100000 non-null  int64
 5   sexo                            100000 non-null  object
 6   estado_civil                    100000 non-null  object
 7   qtde_filhos                     100000 non-null  int64
 8   estado                          100000 non-null  object
 9   regiao                          100000 non-null  object
 10  cidade_porte                    100000 non-null  object
 11  profissao_grupo                 100000 non-null  object
 12  renda_mensal_estimada           92075 non-null   float64
 13  score_credito                   93991 non-null   float64
 14  tempo_habilitacao_anos          100000 non-null  float64
 15  pontos_cnh                      100000 non-null  int64
 16  multas_24m                      100000 non-null  int64
 17  multas_graves_24m               100000 non-null  int64
 18  sinistros_anteriores            100000 non-null  int64
 19  sinistros_12m_anteriores        100000 non-null  int64
 20  acionamentos_guincho_24m        100000 non-null  int64
 21  cancelamento_apolice_anterior   100000 non-null  int64
 22  marca                           100000 non-null  object
 23  modelo                          100000 non-null  object
 24  ano_fabricacao                  100000 non-null  int64
 25  ano_modelo                      100000 non-null  int64
 26  idade_veiculo                   100000 non-null  int64
 27  categoria_veiculo               100000 non-null  object
 28  tipo_combustivel                100000 non-null  object
 29  cambio                          100000 non-null  object
 30  potencia_cv                     92957 non-null   float64
 31  valor_veiculo                   94346 non-null   float64
 32  km_total                        100000 non-null  int64
 33  uso_principal                   100000 non-null  object
 34  usa_carro_para_trabalho         100000 non-null  int64
 35  frequencia_uso_semana           100000 non-null  int64
 36  km_por_ano_estimado             90399 non-null   float64
 37  periodo_uso_predominante        100000 non-null  object
 38  circula_em_rodovia              100000 non-null  int64
 39  regiao_circulacao_risco         100000 non-null  object
 40  possui_garagem_residencial      100000 non-null  int64
 41  tipo_garagem_residencial        100000 non-null  object
 42  possui_garagem_trabalho         100000 non-null  int64
 43  tipo_estacionamento_trabalho    100000 non-null  object
 44  dorme_na_rua_frequencia         100000 non-null  object
 45  revisoes_em_dia                 100000 non-null  int64
 46  qtde_revisoes_24m               100000 non-null  int64
 47  atraso_medio_revisao_dias       100000 non-null  float64
 48  troca_pneus_24m                 100000 non-null  int64
 49  troca_freios_24m                100000 non-null  int64
 50  historico_manutencao_score      92009 non-null   float64
 51  alertas_manutencao_ativos       100000 non-null  int64
 52  valor_segurado                  99990 non-null   float64
 53  premio_seguro                   100000 non-null  float64
 54  franquia                        100000 non-null  float64
 55  tipo_cobertura                  100000 non-null  object
 56  assistencia_24h                 100000 non-null  int64
 57  carro_reserva                   100000 non-null  int64
 58  protecao_vidros                 100000 non-null  int64
 59  classe_bonus                    100000 non-null  int64
 60  desconto_comercial              95960 non-null   float64
 61  sinistro_grave_perda_total_12m  100000 non-null  int64
dtypes: float64(12), int64(31), object(19)
memory usage: 47.3+ MB

In [3]:
df.describe()

,id_cliente,ano_contratacao,mes_contratacao,idade,qtde_filhos,renda_mensal_estimada,score_credito,tempo_habilitacao_anos,pontos_cnh,multas_24m,...,alertas_manutencao_ativos,valor_segurado,premio_seguro,franquia,assistencia_24h,carro_reserva,protecao_vidros,classe_bonus,desconto_comercial,sinistro_grave_perda_total_12m
count,100000.000000,100000.00000,100000.00000,100000.000000,100000.000000,92075.000000,93991.000000,100000.000000,100000.000000,100000.000000,...,100000.00000,9.999000e+04,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,95960.000000,100000.000000
mean,149999.500000,2022.85476,6.48982,40.927260,1.084530,7776.168519,853.557032,20.363907,3.830750,0.918590,...,1.13536,9.201110e+04,2878.851157,4378.257661,0.527510,0.478630,0.442230,6.605790,8.879333,0.064680
std,28867.657797,1.58094,3.44815,12.938238,1.114952,6554.247355,105.917952,12.672101,6.114139,1.337146,...,1.34776,8.204714e+04,6490.850971,4171.060205,0.499245,0.499546,0.496654,3.811839,5.023261,0.245962
min,100000.000000,2020.00000,1.00000,12.000000,-3.000000,-43989.720000,-50.000000,0.000000,0.000000,0.000000,...,0.00000,-3.493290e+05,-9880.010000,900.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,124999.750000,2022.00000,3.00000,31.000000,0.000000,4065.320000,782.000000,10.100000,0.000000,0.000000,...,0.00000,3.862221e+04,1239.570000,1707.672500,0.000000,0.000000,0.000000,3.000000,5.240000,0.000000
50%,149999.500000,2023.00000,6.00000,41.000000,1.000000,5937.500000,866.000000,20.000000,0.000000,0.000000,...,1.00000,6.414538e+04,1892.345000,2934.665000,1.000000,0.000000,0.000000,8.000000,8.760000,0.000000
75%,174999.250000,2024.00000,9.00000,50.000000,2.000000,9064.530000,945.000000,29.400000,5.000000,1.000000,...,2.00000,1.122963e+05,3213.692500,5372.702500,1.000000,1.000000,1.000000,10.000000,12.310000,0.000000
max,199999.000000,2025.00000,12.00000,120.000000,8.000000,80000.000000,1500.000000,71.000000,40.000000,11.000000,...,10.00000,1.092909e+06,630929.146735,30000.000000,1.000000,1.000000,1.000000,10.000000,33.890000,1.000000